### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by codecaiine** [codecaiine/space-travelers-hub#25]
- Set up an empty repo by @Isabellanamutenda  and @codecaiine
- Collaborators assigned: Isabella and Yannick 
- Project Link :   https://github.com/codecaiine/space-travelers-hub/projects

**Comment by henatan99** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] OPTIONAL: You should have added the project number in the URL address so that one can directly land on the particular project you are working on. Assume you have multiple projects and the reviewer will get confused about which project you are currently working on.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by codecaiine** [comment]
Hi @henatan99, 
Thanks for reviewing our works. And also for your approval .
Cheers !
